/*
 * This file is generated by jOOQ.
 */
package com.sairam.books.internal.access.models.jooq;


import com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations;
import com.sairam.books.internal.access.models.jooq.tables.Authors;
import com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Books extends SchemaImpl {

    private static final long serialVersionUID = 731837881;

    /**
     * The reference instance of <code>books</code>
     */
    public static final Books BOOKS = new Books();

    /**
     * The table <code>books.authors</code>.
     */
    public final Authors AUTHORS = com.sairam.books.internal.access.models.jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>books.author_book_relations</code>.
     */
    public final AuthorBookRelations AUTHOR_BOOK_RELATIONS = com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations.AUTHOR_BOOK_RELATIONS;

    /**
     * The table <code>books.books</code>.
     */
    public final com.sairam.books.internal.access.models.jooq.tables.Books BOOKS_ = com.sairam.books.internal.access.models.jooq.tables.Books.BOOKS_;

    /**
     * The table <code>books.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Books() {
        super("books", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authors.AUTHORS,
            AuthorBookRelations.AUTHOR_BOOK_RELATIONS,
            com.sairam.books.internal.access.models.jooq.tables.Books.BOOKS_,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }
}
