/*
 * This file is generated by jOOQ.
 */
package com.sairam.books.internal.access.models.jooq;


import com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations;
import com.sairam.books.internal.access.models.jooq.tables.Authors;
import com.sairam.books.internal.access.models.jooq.tables.Books;
import com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>books</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTHORS_PRIMARY = Indexes0.AUTHORS_PRIMARY;
    public static final Index AUTHOR_BOOK_RELATIONS_BOOK_ID = Indexes0.AUTHOR_BOOK_RELATIONS_BOOK_ID;
    public static final Index AUTHOR_BOOK_RELATIONS_PRIMARY = Indexes0.AUTHOR_BOOK_RELATIONS_PRIMARY;
    public static final Index BOOKS_PRIMARY = Indexes0.BOOKS_PRIMARY;
    public static final Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Indexes0.FLYWAY_SCHEMA_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUTHORS_PRIMARY = Internal.createIndex("PRIMARY", Authors.AUTHORS, new OrderField[] { Authors.AUTHORS.ID }, true);
        public static Index AUTHOR_BOOK_RELATIONS_BOOK_ID = Internal.createIndex("book_id", AuthorBookRelations.AUTHOR_BOOK_RELATIONS, new OrderField[] { AuthorBookRelations.AUTHOR_BOOK_RELATIONS.BOOK_ID }, false);
        public static Index AUTHOR_BOOK_RELATIONS_PRIMARY = Internal.createIndex("PRIMARY", AuthorBookRelations.AUTHOR_BOOK_RELATIONS, new OrderField[] { AuthorBookRelations.AUTHOR_BOOK_RELATIONS.AUTHOR_ID, AuthorBookRelations.AUTHOR_BOOK_RELATIONS.BOOK_ID }, true);
        public static Index BOOKS_PRIMARY = Internal.createIndex("PRIMARY", Books.BOOKS_, new OrderField[] { Books.BOOKS_.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    }
}
