/*
 * This file is generated by jOOQ.
 */
package com.sairam.books.internal.access.models.jooq;


import com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations;
import com.sairam.books.internal.access.models.jooq.tables.Authors;
import com.sairam.books.internal.access.models.jooq.tables.Books;
import com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory;
import com.sairam.books.internal.access.models.jooq.tables.records.AuthorBookRelationsRecord;
import com.sairam.books.internal.access.models.jooq.tables.records.AuthorsRecord;
import com.sairam.books.internal.access.models.jooq.tables.records.BooksRecord;
import com.sairam.books.internal.access.models.jooq.tables.records.FlywaySchemaHistoryRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>books</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = UniqueKeys0.KEY_AUTHORS_PRIMARY;
    public static final UniqueKey<AuthorBookRelationsRecord> KEY_AUTHOR_BOOK_RELATIONS_PRIMARY = UniqueKeys0.KEY_AUTHOR_BOOK_RELATIONS_PRIMARY;
    public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = UniqueKeys0.KEY_BOOKS_PRIMARY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = UniqueKeys0.KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthorBookRelationsRecord, AuthorsRecord> AUTHOR_BOOK_RELATIONS_IBFK_1 = ForeignKeys0.AUTHOR_BOOK_RELATIONS_IBFK_1;
    public static final ForeignKey<AuthorBookRelationsRecord, BooksRecord> AUTHOR_BOOK_RELATIONS_IBFK_2 = ForeignKeys0.AUTHOR_BOOK_RELATIONS_IBFK_2;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AuthorsRecord> KEY_AUTHORS_PRIMARY = Internal.createUniqueKey(Authors.AUTHORS, "KEY_authors_PRIMARY", Authors.AUTHORS.ID);
        public static final UniqueKey<AuthorBookRelationsRecord> KEY_AUTHOR_BOOK_RELATIONS_PRIMARY = Internal.createUniqueKey(AuthorBookRelations.AUTHOR_BOOK_RELATIONS, "KEY_author_book_relations_PRIMARY", AuthorBookRelations.AUTHOR_BOOK_RELATIONS.AUTHOR_ID, AuthorBookRelations.AUTHOR_BOOK_RELATIONS.BOOK_ID);
        public static final UniqueKey<BooksRecord> KEY_BOOKS_PRIMARY = Internal.createUniqueKey(Books.BOOKS_, "KEY_books_PRIMARY", Books.BOOKS_.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> KEY_FLYWAY_SCHEMA_HISTORY_PRIMARY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "KEY_flyway_schema_history_PRIMARY", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AuthorBookRelationsRecord, AuthorsRecord> AUTHOR_BOOK_RELATIONS_IBFK_1 = Internal.createForeignKey(com.sairam.books.internal.access.models.jooq.Keys.KEY_AUTHORS_PRIMARY, AuthorBookRelations.AUTHOR_BOOK_RELATIONS, "author_book_relations_ibfk_1", AuthorBookRelations.AUTHOR_BOOK_RELATIONS.AUTHOR_ID);
        public static final ForeignKey<AuthorBookRelationsRecord, BooksRecord> AUTHOR_BOOK_RELATIONS_IBFK_2 = Internal.createForeignKey(com.sairam.books.internal.access.models.jooq.Keys.KEY_BOOKS_PRIMARY, AuthorBookRelations.AUTHOR_BOOK_RELATIONS, "author_book_relations_ibfk_2", AuthorBookRelations.AUTHOR_BOOK_RELATIONS.BOOK_ID);
    }
}
