/*
 * This file is generated by jOOQ.
 */
package com.sairam.books.internal.access.models.jooq;


import com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations;
import com.sairam.books.internal.access.models.jooq.tables.Authors;
import com.sairam.books.internal.access.models.jooq.tables.Books;
import com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in books
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>books.authors</code>.
     */
    public static final Authors AUTHORS = com.sairam.books.internal.access.models.jooq.tables.Authors.AUTHORS;

    /**
     * The table <code>books.author_book_relations</code>.
     */
    public static final AuthorBookRelations AUTHOR_BOOK_RELATIONS = com.sairam.books.internal.access.models.jooq.tables.AuthorBookRelations.AUTHOR_BOOK_RELATIONS;

    /**
     * The table <code>books.books</code>.
     */
    public static final Books BOOKS_ = com.sairam.books.internal.access.models.jooq.tables.Books.BOOKS_;

    /**
     * The table <code>books.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.sairam.books.internal.access.models.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
